export { default as Avatar} from './Avatar'
export { default as Button } from './Button'
export { default as Footer } from './Footer'
export { default as Input } from './Input'
export { default as Page } from './Page'
